version: '3.7'

services: # Todos los servicios (contenedores) que se desean ejecutar se definen bajo esta sección.

  vault: # Nombre del servicio. Puede ser cualquier cosa, pero en este caso, lo llamamos "vault".
    container_name: vault-compose-bridge
    image: hashicorp/vault  # Especifica la imagen que se va a usar para este servicio.
    volumes:
      - /vault-data:/vault/data
    # Las variables de entorno se establecen con la clave "environment". Estas variables serán pasadas al contenedor cuando se inicie.
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=my-secret-root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8300

    # La clave 'cap_add' se utiliza para agregar capacidades al contenedor. En este caso, estamos agregando 'IPC_LOCK' que es necesario para que Vault bloquee la memoria.
    cap_add:
      - IPC_LOCK
    networks:
      - jenkins-vault

    # La clave 'ports' se utiliza para mapear puertos desde el contenedor al host. El formato es 'puerto_host:puerto_contenedor'.
    ports:
      - 8300:8200
  jenkins_service:
    container_name: compose-jenkins-service--bridge
    image: jenkins/jenkins:alpine
    ports:
      - 8181:8080
      - 5000:5000
    volumes:
      - /windows-personal-store/jenkins/jenkins-alpine:/personal-store/jenkins/jenkins-alpine
    networks:
      - jenkins-vault
networks:
  jenkins-vault:
    name: jenkins-vault
    driver: bridge